//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeToanCau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class airport_way
    {
        public int id { get; set; }
        public string airport_name { get; set; }
        public Nullable<double> lon1 { get; set; }
        public Nullable<double> lat1 { get; set; }
        public Nullable<double> lon2 { get; set; }
        public Nullable<double> lat2 { get; set; }
    }
}
