//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeToanCau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_price
    {
        public int ID { get; set; }
        public Nullable<int> car_size { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> multiple { get; set; }
        public Nullable<double> multiple2 { get; set; }
    }
}
