//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeToanCau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_price_airport
    {
        public int id { get; set; }
        public string airport_name { get; set; }
        public Nullable<int> car_size { get; set; }
        public Nullable<int> price_go_way { get; set; }
        public Nullable<int> price_back_way { get; set; }
        public Nullable<int> price_two_way { get; set; }
    }
}
