//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeToanCau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public long id { get; set; }
        public string custom_name { get; set; }
        public string custom_phone { get; set; }
        public string custom_email { get; set; }
        public string regId { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> date_reg { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<int> os { get; set; }
    }
}
