//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeToanCau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class info
    {
        public int id { get; set; }
        public string hotline1 { get; set; }
        public string hotline2 { get; set; }
        public string about { get; set; }
        public string address { get; set; }
    }
}
