//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeToanCau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saoke
    {
        public long id { get; set; }
        public Nullable<long> id_driver { get; set; }
        public Nullable<long> id_booking { get; set; }
        public Nullable<int> money { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    }
}
