//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeToanCau.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class thuexetoancauEntities : DbContext
    {
        public thuexetoancauEntities()
            : base("name=thuexetoancauEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<list_car> list_car { get; set; }
        public virtual DbSet<list_car_model> list_car_model { get; set; }
        public virtual DbSet<list_car_type> list_car_type { get; set; }
        public virtual DbSet<TinhThanh> TinhThanhs { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<driver> drivers { get; set; }
        public virtual DbSet<NationalDay> NationalDays { get; set; }
        public virtual DbSet<car_hire_type> car_hire_type { get; set; }
        public virtual DbSet<car_price> car_price { get; set; }
        public virtual DbSet<car_type> car_type { get; set; }
        public virtual DbSet<car_who_hire> car_who_hire { get; set; }
        public virtual DbSet<notice> notices { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
    }
}
